#---
# EPEL Repository for extra packages
epel_repo: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
# Select ELK version 6x or 7x
elk_version: 7x
# The hostname of the server that is going to run the ELK stack
server_name: elk
# -- Nginx Variables --
# The port that Nginx listens to that is forwarded to Kibana's local port
nginx_kibana_port: 80
# Nginx SSL listening port
elk_server_ssl_cert_port: 8080
# The web authentication credentials to gain access to Kibana
kibana_user: admin
kibana_password: admin
# The system user that Nginx will use
nginx_user: www-data
# The IP address of the ELK server that is going to be installed
elk_ip: 127.0.0.1
