---
#
# Playbook to install the ELK stack
#
- hosts: elk
  remote_user: user
  become: yes
  become_user: root
  gather_facts: true
  roles:
   - { role: java }
   - { role: elasticsearch }
   - { role: kibana }
   - { role: nginx }
   - { role: logstash }
