---
#
# Playbook to install the ELK stack
#
- hosts: elk
  remote_user: ec2-user
  become: yes
  gather_facts: true
  roles:
   - { role: java }
   - { role: elasticsearch }
   - { role: kibana }
   - { role: nginx }
   - { role: logstash }
