---
#
# Installing Kibana
#
# Add Kibana yum-repository
- name: Adding Kibana repository
  copy:
    src=kibana-{{ elk_version }}.repo
    dest=/etc/yum.repos.d/kibana-{{ elk_version }}.repo
    owner=root
    group=root
    mode=0644
  become: true
# Install Kibana
- name: Update repositories cache and install Kibana
  yum:
   name: kibana
   update_cache: yes
# Update kibana config file to only accept local connections
#- name: Updating the config file to restrict outside access
#  lineinfile:
#   destfile: /etc/kibana/kibana.yml
#   regexp: 'server.host:'
#   line: 'server.host: localhost'
- name: Updating the kibana configurations
  template:
   src=kibana.yml.j2
   dest=/etc/kibana/kibana.yml
   owner=root
   group=kibana
   mode=0660
   force=yes
# Enable Kibana service
- name: Enabling Kibana service
  systemd:
   name: kibana
   enabled: yes
   daemon_reload: yes
  become: true
# Start Kibana service
- name: Starting Kibana service
  systemd:
   name: kibana
   state: started
