---
#
# Installing Elasticsearch
#
# Add the Elasticsearch yum-repository
- name: Copy elasticsearch yum repo file
  copy:
    src=elasticsearch-{{ elk_version }}.repo
    dest=/etc/yum.repos.d/elasticsearch-{{ elk_version }}.repo
    owner=root
    group=root
    mode=0644
  become: true
# Install Elasticsearch
- name: Update repositories cache and install Elasticsearch
  yum:
   name: elasticsearch
   update_cache: yes
  become: true
# Update Elasticsearch config file to only allow localhost connections
#- name: Updating the config file to restrict outside access
#  lineinfile:
#   destfile: /etc/elasticsearch/elasticsearch.yml
#   regexp: 'network.host:'
#   line: 'network.host: localhost'
# Update Cluster Configurations
# Writes the create user script in the temp directory
- name: Updating the cluster configurations
  template:
   src=elasticsearch.yml.j2
   dest=/etc/elasticsearch/elasticsearch.yml
   owner=root
   group=root
   mode=0660
   force=yes
# Restart Elasticsearch
- name: Restarting Elasticsearch
  service:
   name: elasticsearch
   state: restarted
